import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import {db,rows} from "./db.js";
import "dotenv/config";

const app=express();const port=Number(process.env.API_PORT||3001);const secret=process.env.JWT_SECRET||"development-secret";
app.use(cors());app.use(express.json({limit:"10mb"}));
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const auth=(req,res,next)=>{const token=req.headers.authorization?.replace("Bearer ","");if(!token)return res.status(401).json({message:"Bạn chưa đăng nhập"});try{req.user=jwt.verify(token,secret);next();}catch{return res.status(401).json({message:"Phiên đăng nhập không hợp lệ"});}};
const admin=(req,res,next)=>req.user.role==="admin"?next():res.status(403).json({message:"Chỉ admin được thực hiện thao tác này"});

app.get("/api/health",asyncRoute(async(_req,res)=>{await rows("SELECT 1");res.json({ok:true,database:"mysql"});}));
app.post("/api/auth/login",asyncRoute(async(req,res)=>{const {email,password}=req.body;const [user]=await rows("SELECT id,campus_id,full_name,email,phone,password_hash,role FROM users WHERE email=? AND active=1",[email]);if(!user||!await bcrypt.compare(password,user.password_hash))return res.status(401).json({message:"Email hoặc mật khẩu không đúng"});delete user.password_hash;res.json({token:jwt.sign(user,secret,{expiresIn:"12h"}),user});}));
app.post("/api/registrations",asyncRoute(async(req,res)=>{const b=req.body;const [r]=await db.execute("INSERT INTO course_registrations(parent_name,phone,email,child_name,age_group,gender,note) VALUES (?,?,?,?,?,?,?)",[b.parentName,b.phone,b.email||null,b.childName,b.ageGroup,b.gender,b.note||null]);res.status(201).json({id:r.insertId});}));

app.use("/api",auth);
app.get("/api/fields/:id",asyncRoute(async(req,res)=>{const [field]=await rows("SELECT * FROM field_layouts WHERE id=?",[req.params.id]);if(!field)return res.status(404).json({message:"Không tìm thấy sơ đồ sân"});res.json(field);}));
app.get("/api/bootstrap",asyncRoute(async(req,res)=>{const campus=req.user.campus_id;const [classes,students,parents,exercises,fields,lessons,templates,rounds,results,children]=await Promise.all([
 rows("SELECT c.*,u.full_name teacher_name,(SELECT COUNT(*) FROM students s WHERE s.class_id=c.id AND s.active=1) student_count FROM classes c LEFT JOIN users u ON u.id=c.teacher_id WHERE c.campus_id=?",[campus]),
 req.user.role==="parent"?rows("SELECT s.*,c.name class_name,c.age_group,ps.parent_id,u.full_name parent_name,ps.relationship FROM parent_students ps JOIN students s ON s.id=ps.student_id LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN users u ON u.id=ps.parent_id WHERE ps.parent_id=?",[req.user.id]):rows("SELECT s.*,c.name class_name,c.age_group,ps.parent_id,u.full_name parent_name,ps.relationship FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN parent_students ps ON ps.student_id=s.id LEFT JOIN users u ON u.id=ps.parent_id WHERE s.campus_id=?",[campus]),
 req.user.role==="parent"?Promise.resolve([]):rows("SELECT u.id,u.full_name,u.email,u.phone,u.active,(SELECT COUNT(*) FROM parent_students ps WHERE ps.parent_id=u.id) child_count FROM users u WHERE u.campus_id=? AND u.role='parent' ORDER BY u.full_name",[campus]),
 rows("SELECT e.*,f.name field_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('score',score,'threshold',threshold_value,'label',label)) FROM scoring_bands b WHERE b.exercise_id=e.id) bands FROM exercises e LEFT JOIN field_layouts f ON f.id=e.field_layout_id"),
 rows("SELECT * FROM field_layouts"), rows("SELECT l.*,f.name field_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('id',e.id,'name',e.name)) FROM lesson_exercises x JOIN exercises e ON e.id=x.exercise_id WHERE x.lesson_id=l.id) exercises FROM lessons l LEFT JOIN field_layouts f ON f.id=l.field_layout_id"),
 rows("SELECT t.*,(SELECT COUNT(*) FROM exam_template_exercises x WHERE x.template_id=t.id) exercise_count,(SELECT JSON_ARRAYAGG(JSON_OBJECT('id',e.id,'name',e.name,'age_group',e.age_group,'category',e.category,'unit',e.unit)) FROM exam_template_exercises x JOIN exercises e ON e.id=x.exercise_id WHERE x.template_id=t.id) exercises FROM exam_templates t"),
 rows("SELECT r.*,t.name template_name,t.age_group template_age,(SELECT JSON_ARRAYAGG(class_id) FROM exam_round_classes x WHERE x.round_id=r.id) class_ids,(SELECT COUNT(*) FROM results z WHERE z.round_id=r.id) result_count,(SELECT COUNT(*) FROM exam_round_classes rc JOIN students s ON s.class_id=rc.class_id WHERE rc.round_id=r.id AND s.active=1) student_count FROM exam_rounds r JOIN exam_templates t ON t.id=r.template_id WHERE r.campus_id=?",[campus]),
 req.user.role==="parent"?rows("SELECT r.*,s.full_name student_name,c.name class_name,er.name round_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('name',JSON_UNQUOTE(JSON_EXTRACT(ri.snapshot,'$.name')),'score',ri.score)) FROM result_items ri WHERE ri.result_id=r.id) items FROM results r JOIN students s ON s.id=r.student_id JOIN parent_students ps ON ps.student_id=s.id LEFT JOIN classes c ON c.id=s.class_id JOIN exam_rounds er ON er.id=r.round_id WHERE ps.parent_id=? AND r.status='published'",[req.user.id]):rows("SELECT r.*,s.full_name student_name,c.name class_name,er.name round_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('name',JSON_UNQUOTE(JSON_EXTRACT(ri.snapshot,'$.name')),'score',ri.score)) FROM result_items ri WHERE ri.result_id=r.id) items FROM results r JOIN students s ON s.id=r.student_id LEFT JOIN classes c ON c.id=s.class_id JOIN exam_rounds er ON er.id=r.round_id WHERE er.campus_id=?",[campus]),
 req.user.role==="parent"?rows("SELECT s.*,c.name class_name,c.age_group FROM parent_students ps JOIN students s ON s.id=ps.student_id LEFT JOIN classes c ON c.id=s.class_id WHERE ps.parent_id=?",[req.user.id]):Promise.resolve([])
]);res.json({classes,students,parents,exercises,fields,lessons,templates,rounds,results,children});}));

app.post("/api/parents",admin,asyncRoute(async(req,res)=>{const b=req.body;const hash=await bcrypt.hash(b.password||"123456",10);const [r]=await db.execute("INSERT INTO users(campus_id,full_name,email,phone,password_hash,role,active) VALUES (?,?,?,?,?,'parent',?)",[req.user.campus_id,b.full_name,b.email,b.phone||null,hash,Number(b.active)===0?0:1]);res.status(201).json({id:r.insertId});}));
app.put("/api/parents/:id",admin,asyncRoute(async(req,res)=>{const b=req.body;await db.execute("UPDATE users SET full_name=?,email=?,phone=?,active=? WHERE id=? AND campus_id=? AND role='parent'",[b.full_name,b.email,b.phone||null,Number(b.active)===0?0:1,req.params.id,req.user.campus_id]);res.json({ok:true});}));
app.delete("/api/parents/:id",admin,asyncRoute(async(req,res)=>{await db.execute("DELETE FROM users WHERE id=? AND campus_id=? AND role='parent'",[req.params.id,req.user.campus_id]);res.status(204).end();}));
app.put("/api/students/:id/parent",admin,asyncRoute(async(req,res)=>{await db.execute("DELETE FROM parent_students WHERE student_id=?",[req.params.id]);if(req.body.parent_id)await db.execute("INSERT INTO parent_students(parent_id,student_id,relationship) SELECT ?,s.id,? FROM students s JOIN users u ON u.id=? AND u.role='parent' WHERE s.id=? AND s.campus_id=?",[req.body.parent_id,req.body.relationship||"Phụ huynh",req.body.parent_id,req.params.id,req.user.campus_id]);res.json({ok:true});}));
app.put("/api/lessons/:id/exercises",admin,asyncRoute(async(req,res)=>{const ids=[...new Set((req.body.exercise_ids||[]).map(Number).filter(Boolean))];const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute("DELETE FROM lesson_exercises WHERE lesson_id=?",[req.params.id]);for(let i=0;i<ids.length;i++)await connection.execute("INSERT INTO lesson_exercises(lesson_id,exercise_id,sort_order) VALUES (?,?,?)",[req.params.id,ids[i],i]);await connection.commit();res.json({ok:true,count:ids.length});}catch(e){await connection.rollback();throw e}finally{connection.release()}}));

const resources={classes:{table:"classes",fields:["campus_id","teacher_id","name","age_group","school_year","active"],admin:true},students:{table:"students",fields:["campus_id","class_id","code","full_name","birth_date","gender","active"],admin:true},exercises:{table:"exercises",fields:["name","age_group","gender","category","unit","score_direction","instruction","field_layout_id","status","created_by"],admin:true},fields:{table:"field_layouts",fields:["name","age_group","gender","tags","equipment","layout_data","status","created_by"],admin:true},lessons:{table:"lessons",fields:["title","age_group","gender","skill","duration_minutes","field_layout_id","content","media","status","created_by"],admin:true},templates:{table:"exam_templates",fields:["name","age_group","gender","status","created_by"],admin:true}};
for(const [path,cfg] of Object.entries(resources)){
 app.post(`/api/${path}`,admin,asyncRoute(async(req,res)=>{const body={...req.body};if(cfg.fields.includes("campus_id")&&!body.campus_id)body.campus_id=req.user.campus_id;if(cfg.fields.includes("created_by")&&!body.created_by)body.created_by=req.user.id;for(const key of ["tags","layout_data","content","media"])if(body[key]&&typeof body[key]!=="string")body[key]=JSON.stringify(body[key]);const keys=cfg.fields.filter(k=>body[k]!==undefined);const [r]=await db.execute(`INSERT INTO ${cfg.table} (${keys.join(",")}) VALUES (${keys.map(()=>"?").join(",")})`,keys.map(k=>body[k]));res.status(201).json({id:r.insertId});}));
 app.put(`/api/${path}/:id`,admin,asyncRoute(async(req,res)=>{const body={...req.body};for(const key of ["tags","layout_data","content","media"])if(body[key]&&typeof body[key]!=="string")body[key]=JSON.stringify(body[key]);const keys=cfg.fields.filter(k=>body[k]!==undefined);await db.execute(`UPDATE ${cfg.table} SET ${keys.map(k=>`${k}=?`).join(",")} WHERE id=?`,[...keys.map(k=>body[k]),req.params.id]);res.json({ok:true});}));
 app.delete(`/api/${path}/:id`,admin,asyncRoute(async(req,res)=>{await db.execute(`DELETE FROM ${cfg.table} WHERE id=?`,[req.params.id]);res.status(204).end();}));
}
app.post("/api/rounds",admin,asyncRoute(async(req,res)=>{const b=req.body;const connection=await db.getConnection();try{await connection.beginTransaction();const [r]=await connection.execute("INSERT INTO exam_rounds(campus_id,template_id,name,exam_type,starts_on,ends_on,status,created_by) VALUES (?,?,?,?,?,?,?,?)",[req.user.campus_id,b.template_id,b.name,b.exam_type,b.starts_on,b.ends_on,b.status||"draft",req.user.id]);for(const classId of b.class_ids)await connection.execute("INSERT INTO exam_round_classes(round_id,class_id,teacher_id) SELECT ?,id,teacher_id FROM classes WHERE id=?",[r.insertId,classId]);await connection.commit();res.status(201).json({id:r.insertId});}catch(e){await connection.rollback();if(e?.code==="ER_DUP_ENTRY")return res.status(409).json({message:"Tên đợt thi đã tồn tại tại cơ sở này"});throw e;}finally{connection.release();}}));
app.delete("/api/rounds/:id",admin,asyncRoute(async(req,res)=>{await db.execute("DELETE FROM exam_rounds WHERE id=?",[req.params.id]);res.status(204).end();}));
app.put("/api/rounds/:id",admin,asyncRoute(async(req,res)=>{const b=req.body;const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute("UPDATE exam_rounds SET name=?,template_id=?,exam_type=?,starts_on=?,ends_on=?,status=? WHERE id=? AND campus_id=?",[b.name,b.template_id,b.exam_type,b.starts_on,b.ends_on,b.status,b.id||req.params.id,req.user.campus_id]);await connection.execute("DELETE FROM exam_round_classes WHERE round_id=?",[req.params.id]);for(const classId of b.class_ids||[])await connection.execute("INSERT INTO exam_round_classes(round_id,class_id,teacher_id) SELECT ?,id,teacher_id FROM classes WHERE id=? AND campus_id=?",[req.params.id,classId,req.user.campus_id]);await connection.commit();res.json({ok:true});}catch(e){await connection.rollback();if(e?.code==="ER_DUP_ENTRY")return res.status(409).json({message:"Tên đợt thi đã tồn tại tại cơ sở này"});throw e;}finally{connection.release();}}));
app.put("/api/templates/:id/exercises",admin,asyncRoute(async(req,res)=>{const ids=[...new Set((req.body.exercise_ids||[]).map(Number).filter(Boolean))];const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute("DELETE FROM exam_template_exercises WHERE template_id=?",[req.params.id]);for(let i=0;i<ids.length;i++)await connection.execute("INSERT INTO exam_template_exercises(template_id,exercise_id,sort_order) VALUES (?,?,?)",[req.params.id,ids[i],i]);await connection.commit();res.json({ok:true,count:ids.length});}catch(e){await connection.rollback();throw e;}finally{connection.release();}}));
app.post("/api/results",asyncRoute(async(req,res)=>{if(!["admin","teacher"].includes(req.user.role))return res.status(403).json({message:"Không có quyền chấm điểm"});const b=req.body;const connection=await db.getConnection();try{await connection.beginTransaction();const average=b.items.reduce((sum,x)=>sum+Number(x.score),0)/(b.items.length||1);const rating=average>=8?"Tốt":average>=6.5?"Đạt":"Cần hỗ trợ";const snapshot=JSON.stringify({campus:b.campus,template:b.template,graded_at:new Date().toISOString(),exercises:b.items.map(x=>x.snapshot)});await connection.execute("INSERT INTO results(round_id,student_id,grader_id,average_score,rating,teacher_comment,status,snapshot,completed_at,published_at) VALUES (?,?,?,?,?,?,?, ?,NOW(),IF(?='published',NOW(),NULL)) ON DUPLICATE KEY UPDATE grader_id=VALUES(grader_id),average_score=VALUES(average_score),rating=VALUES(rating),teacher_comment=VALUES(teacher_comment),status=VALUES(status),snapshot=VALUES(snapshot),completed_at=NOW(),published_at=IF(VALUES(status)='published',NOW(),published_at)",[b.round_id,b.student_id,req.user.id,average,rating,b.teacher_comment||null,b.status||"completed",snapshot,b.status||"completed"]);const [[result]]=await connection.query("SELECT id FROM results WHERE round_id=? AND student_id=?",[b.round_id,b.student_id]);await connection.execute("DELETE FROM result_items WHERE result_id=?",[result.id]);for(const item of b.items)await connection.execute("INSERT INTO result_items(result_id,exercise_id,raw_value,score,snapshot) VALUES (?,?,?,?,?)",[result.id,item.exercise_id,item.raw_value||null,item.score,JSON.stringify(item.snapshot)]);await connection.commit();res.json({id:result.id,average,rating});}catch(e){await connection.rollback();throw e;}finally{connection.release();}}));
app.patch("/api/results/:id/publish",admin,asyncRoute(async(req,res)=>{await db.execute("UPDATE results SET status='published',published_at=NOW() WHERE id=?",[req.params.id]);res.json({ok:true});}));
app.get("/api/parent/children/:id/results",asyncRoute(async(req,res)=>{if(req.user.role==="parent"){const [linked]=await rows("SELECT 1 ok FROM parent_students WHERE parent_id=? AND student_id=?",[req.user.id,req.params.id]);if(!linked)return res.status(403).json({message:"Học sinh không thuộc tài khoản này"});}res.json(await rows("SELECT r.*,er.name round_name,er.exam_type,er.starts_on FROM results r JOIN exam_rounds er ON er.id=r.round_id WHERE r.student_id=? AND r.status='published' ORDER BY er.starts_on DESC",[req.params.id]));}));
app.use((err,_req,res,_next)=>{console.error(err);res.status(err.code==="ECONNREFUSED"?503:500).json({message:err.code==="ECONNREFUSED"?"Không kết nối được MySQL. Hãy kiểm tra file .env và chạy yarn db:init.":err.message||"Lỗi máy chủ"});});
app.listen(port,"127.0.0.1",()=>console.log(`API Sakura Motion: http://127.0.0.1:${port}`));
