import type { PaletteItem } from './App';

export const objectLibrary: Omit<PaletteItem, 'id'>[] = [
    {
        type: 'custom',
        label: 'Người chơi đỏ',
        w: 1,
        h: 1,
        image: '/assets/hinh_nguoi_mau_do.png',
        rotate: 0,
        locked: true,
    },
    {
        type: 'custom',
        label: 'Người chơi vàng',
        w: 1,
        h: 1,
        image: '/assets/hinh_nguoi_mau_vang.png',
        rotate: 0,
        locked: true,
    },
    {
        type: 'custom',
        label: 'Bóng',
        w: 1,
        h: 1,
        image: '/assets/Bong.png',
        rotate: 0,
        locked: true,
    },
    {
        type: 'custom',
        label: 'Cầu thăng bằng',
        w: 1,
        h: 1,
        image: '/assets/cau_thang_bang.png',
        rotate: 0,
        locked: true,
    },
    {
        type: 'custom',
        label: 'Cột bóng rổ',
        w: 1,
        h: 1,
        image: '/assets/cot_bong_ro.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'cột gôn',
        w: 1,
        h: 1,
        image: '/assets/cot_gon.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Cột',
        w: 1,
        h: 1,
        image: '/assets/cot.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Chấm màu đỏ',
        w: 1,
        h: 1,
        image: '/assets/cham_mau_do.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Chấm màu xanh',
        w: 1,
        h: 1,
        image: '/assets/cham_mau_xanh.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'hộp nhảy',
        w: 1,
        h: 1,
        image: '/assets/hop_nhay.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'nón cao màu cam',
        w: 1,
        h: 1,
        image: '/assets/non_cao_mau_cam.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Nón cao màu vàng',
        w: 1,
        h: 1,
        image: '/assets/non_cao_mau_vang.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Nón cao màu xanh',
        w: 1,
        h: 1,
        image: '/assets/non_cao_mau_xanh.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Nón thấp màu đỏ',
        w: 1,
        h: 1,
        image: '/assets/non_thap_mau_do.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Nón thấp màu vàng',
        w: 1,
        h: 1,
        image: '/assets/non_thap_mau_vang.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Nón thấp màu xanh',
        w: 1,
        h: 1,
        image: '/assets/non_thap_mau_xanh.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Ống chui',
        w: 1,
        h: 1,
        image: '/assets/ong.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'quay đầu',
        w: 1,
        h: 1,
        image: '/assets/quay_dau.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Rào cản cao',
        w: 1,
        h: 1,
        image: '/assets/rao_can_cao.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Rào cản',
        w: 1,
        h: 1,
        image: '/assets/rao_can.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Rổ',
        w: 1,
        h: 1,
        image: '/assets/ro.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Thảm',
        w: 1,
        h: 1,
        image: '/assets/tham.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Thang dây',
        w: 1,
        h: 1,
        image: '/assets/thang_day.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Vòng tròn màu vàng',
        w: 1,
        h: 1,
        image: '/assets/vong_tron_mau_vang.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Vòng tròn màu xanh',
        w: 1,
        h: 1,
        image: '/assets/vong_tron_mau_xanh.png',
        rotate: 0,
        locked: true,
    },
        {
        type: 'custom',
        label: 'Xà đơn',
        w: 1,
        h: 1,
        image: '/assets/xa_don.png',
        rotate: 0,
        locked: true,
    },

];